## Title: Grass endophyte population model with a bayesian framework
## Purpose: Creates seed production kernel written in STAN, 
## and does visualisation of posterior predictive checks
## Authors: Joshua and Tom
#############################################################

library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
library(bayesplot)
library(devtools)

invlogit<-function(x){exp(x)/(1+exp(x))}
logit = function(x) { log(x/(1-x)) }


#############################################################################################
####### Data manipulation to prepare data as lists for Stan models------------------
#############################################################################################

# seed data lists are generated in the endodemog_data_processing.R file, 
# within the section titled "Preparing datalists for Seed Means Kernel"
source("endodemog_data_processing.R")

#########################################################################################################
# Stan model for mean of seed production ------------------------------
#########################################################################################################
## run this code to optimize computer system settings for MCMC
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
set.seed(123)

## MCMC settings
ni <-10000
nb <- 5000
nc <- 3

# Stan model -------------
## here is the Stan model ##

sink("endodemog_seed_mean.stan")
cat("
    data { 
    int<lower=0> Nseed;                       // number of observations of seed/spikelet
    real<lower=0> seed[Nseed];               // number of seeds per spikelet
    }
    
    
    parameters {
    real<lower=0> mu_seed;
    real<lower=0> sigma_seed;
    }
    
    model {

    // Priors
    // Likelihood
      seed ~ normal(mu_seed,sigma_seed);
    }

    ", fill = T)
sink()

stanmodel <- stanc("endodemog_seed_mean.stan")

## Run the model by calling stan()
## Save the outputs as rds files
smFESU <- stan(file = "endodemog_seed_mean.stan", data = FESU_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smFESU, file = "endodemog_seed_mean_FESU.rds")

smLOAR <- stan(file = "endodemog_seed_mean.stan", data = LOAR_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smLOAR, file = "endodemog_seed_mean_LOAR.rds")

smPOAL <- stan(file = "endodemog_seed_mean.stan", data = POAL_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smPOAL, file = "endodemog_seed_mean_POAL_withplot.rds")

smPOSY <- stan(file = "endodemog_seed_mean.stan", data = POSY_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smPOSY, file = "endodemog_seed_mean_POSY_withplot.rds")

# AGPE had data recorded as seed/spikelet already, but we are using this model to calculate seed/spikelet on average, so this is using the seed/spikelet info from AGPE
smAGPE<- stan(file = "endodemog_seed_mean.stan", data = AGPE_seed_data_list,
              iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smAGPE, file = "endodemog_seed_mean_AGPE.rds")


# ELRI and ELVI had data collected in a slightly different way. They recorded seeds/inflorescence, so this is our calculation for the mean seeds/infl
smELRI <- stan(file = "endodemog_seed_mean.stan", data = ELRI_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smELRI, file = "endodemog_seed_mean_ELRI.rds")

smELVI <- stan(file = "endodemog_seed_mean.stan", data = ELVI_seed_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smELVI, file = "endodemog_seed_mean_ELVI.rds")

########################################################################################################################################
##### Using the seed means to get seed production estimates 
########################################################################################################################################
# For the non-Elymus species, this function uses the posteriors generated by the model and the measured reproductive data to estimate seed production (currently I'm generating this in three different ways because I'm not sure what the best way to incorporate the measurements is)
est_seed <- function(post,data){
set.seed(5-1-2019)
est <- data
est$seedperspike_est <-sample(post$mu_seed, size = nrow(data))
est$spikeperinf_est <- sample(post$mu_spike, size = nrow(data))
est$seed_a<- as.integer(data$seedperspike*sample(post$mu_spike, size = nrow(data))*data$flw)
est$seed_b <- as.integer(sample(post$mu_seed, size = nrow(data))*data$spikeperinf*data$flw)
est$seed <- as.integer(sample(post$mu_seed, size = nrow(data))*sample(post$mu_spike, size = nrow(data))*data$flw) # this is the seed estimate I'm using for now.
est$seed_norma <- as.integer(data$seedperspike*rnorm(mean = mean(post$mu_spike), sd = mean(post$sigma_spike), n = nrow(data))*data$flw)
est$seed_normb <- as.integer(rnorm(mean = mean(post$mu_seed),sd = mean(post$sigma_seed), n = nrow(data))*data$spikeperinf*data$flw)
est$seed_normc <- as.integer(rnorm(mean = mean(post$mu_seed), sd = mean(post$sigma_seed), n = nrow(data))*rnorm(mean = mean(post$mu_spike), sd = mean(post$sigma_spike), n= nrow(data))*data$flw)

return(est)
}


# calculate POAL seed estimate
POAL_post <- as.data.frame(smPOAL)
POAL_seed_est <- est_seed(post = POAL_post, data = POAL_seed_data) %>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)

# calculate POSY seed estimate
POSY_post <- as.data.frame(smPOSY)
POSY_seed_est <- est_seed(post = POSY_post, data = POSY_seed_data) %>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate FESU seed estimate
FESU_post <- as.data.frame(smFESU)
FESU_seed_est <- est_seed(post = FESU_post, data = FESU_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate LOAR seed estimate
LOAR_post <- as.data.frame(smLOAR)
LOAR_seed_est <- est_seed(post = LOAR_post, data = LOAR_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate AGPE seed estimate
AGPE_post <- as.data.frame(smAGPE)
AGPE_seed_est <- est_seed(post = AGPE_post, data = AGPE_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)



# For the Elymus species, this function uses the posteriors generated by the model and the measured reproductive data to estimate seed production (currently I'm generating this in three different ways because I'm not sure what the best way to incorporate the measurements is)
est_seed_Elymus <- function(post,data){
  set.seed(5-1-2019)
  est <- data
  est$seedperinf_est <-sample(post$mu_seed, size = nrow(data))
  est$seedperinf_normest <- rnorm(mean = mean(post$mu_seed), sd = mean(post$sigma_seed), n = nrow(data))
  est$seed_a <- as.integer(data$seedperinf*data$flw)
  est$seed <- as.integer(sample(post$mu_seed, size = nrow(data))*data$flw) #This is the seed estimate I'm using for now
  est$seed_normb <- as.integer(rnorm(mean = mean(post$mu_seed), sd = mean(post$sigma_seed), n= nrow(data))*data$flw)
  return(est)
}

# calculate ELRI seed estimate
ELRI_post <- as.data.frame(smELRI)
ELRI_seed_est <- est_seed_Elymus(post = ELRI_post, data = ELRI_seed_data)%>% 
  select(-seed_a, -seedperinf_est, -seedperinf_normest,  -seed_normb)


# calculate ELVI seed estimate
ELVI_post <- as.data.frame(smELVI)
ELVI_seed_est <- est_seed_Elymus(post = ELVI_post, data = ELVI_seed_data)%>% 
  select(-seed_a, -seedperinf_est, -seedperinf_normest,  -seed_normb)





# Now I am going to merge the seed estimates for the different species into one dataframe. This will be merged with endo_demog_long for the seed to seedling transition rate.
seed_est_data <- ELVI_seed_est %>% 
  merge(ELRI_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(AGPE_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(FESU_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(LOAR_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(POAL_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(POSY_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE)
  

# View(seed_est_data)
# getting a dataframe with seed_t and seed_t1
seed_est_t1 <-seed_est_data %>%
  filter(year!= min(year)) %>% 
  rename(year_t1 = year, seed_t1 = seed, flw_t1 = flw) %>%  
  mutate(year_t = year_t1 - 1) %>% 
  select(-samplesize, -seedperinf, -seedperspike, -spikeperinf, -year_index)

seed_est_t <- seed_est_data %>%
  filter(year != max(year)) %>% 
  rename(year_t = year, seed_t = seed, flw_t = flw) %>% 
  mutate(year_t1 = year_t + 1) %>% 
  select(-samplesize, -seedperinf, -seedperspike, -spikeperinf, -year_index)


seed_estmerge <- seed_est_t1 %>% 
  full_join(seed_est_t, by = c("plot", "tag", "endo_01", "endo_index", "year_t", "year_t1", "species", "plot_index"),
            all.x = all, all.y = all)




# I'm going to merge this with the main data frame
# This needs to be merged with the rest of the flower data.
LTREB_endodemog <-  read.csv(file = "/Users/joshuacfowler/Dropbox/EndodemogData/Fulldataplusmetadata/endo_demog_long.csv")

LTREB_data_seed_est <- LTREB_endodemog %>% 
  rename(tag = id) %>% 
  select(-seed_t, -seed_t1, -flw_t1) %>% 
  merge(seed_estmerge, by = c("plot", "tag", "species", "year_t", "year_t1"), all = TRUE)
# View(LTREB_data_seed_est)


hist(AGPE_seed_est$seed)
hist(ELVI_seed_est$seed)
hist(ELRI_seed_est$seed)
hist(LOAR_seed_est$seed)
hist(POAL_seed_est$seed)
hist(POSY_seed_est$seed)
hist(FESU_seed_est$seed)
