---
title: "endodemog_figures"
author: "Joshua and Tom"
date: "5/24/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Purpose: 
Visualizes output of endophyte effect on year variance from model outputs for Survival, Growth, Fertility, and Recruitment models. 

# source in R packages and load model outputs
```{r model outputs, include=FALSE}
source('endodemog_model_outputs.R')
```

```{r raw data processing, include=FALSE}
source('endodemog_data_processing.R')
```

```{r colorpalletes, include = FALSE}
#Looking at different color palettes
# Classic palette BuPu, with 4 colors
purps = brewer.pal(9, "Purples")
bupu = brewer.pal(9,"BuPu")
oran = brewer.pal(9, "Oranges")


brewer.pal(9, "Oranges")
orrd = brewer.pal(9, "OrRd")
# I can add more tones to this palette :
purps = colorRampPalette(purps)(11)
# pie(rep(1, length(purps)), col = purps , main="")
bupu = colorRampPalette(bupu)(11)
# pie(rep(1, length(bupu)), col = bupu , main="")
oran = colorRampPalette(oran)(11)
# pie(rep(1, length(oran)), col = oran , main="")
orrd = colorRampPalette(orrd)(11)
# pie(rep(1, length(orrd)), col = orrd , main="")

yearcolors <- c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99",
                "#e31a1c","#fdbf6f","#ff7f00","#cab2d6","#6a3d9a",
                "#ffff99")
colors2 <- c("#ff7f00","#6a3d9a") #"#ff7f00" = E-, "#e31a1c" = E+
```

Plots of variance posteriors
```{r variance histogram gg objects, include=FALSE}
# Variance posterior distributions by species
# This function has code to do either two distributions of the variance between e+ and e- or a distribution of the difference between the two
variance_histogram <- function(df){
  require(ggplot2)
  df$diff_sigma_e <- df$`sigma_e[1]` - df$`sigma_e[2]`
  spp <- ggplot() +
    geom_histogram(data = df, aes(`sigma_e[1]`), fill = "#ff7f00", alpha = .4, bins = 200) +
    geom_histogram(data = df, aes(`sigma_e[2]`), fill = "#6a3d9a", alpha = .4, bins = 200) +
    # geom_histogram(data = df, aes(diff_sigma_e), fill = "#4d9158", alpha = .6, bins = 200) +
    # geom_vline(xintercept = 0) +
    # geom_vline(xintercept = mean(df$diff_sigma_e), col = "#4d9158") + 
    # ylim(0,2500) +
    labs(x = expression(σ[year]), y = "Posterior density") + theme_classic() + theme(axis.title=element_text(size=30), axis.text = element_text(size=20))
  return(spp)
}
# survival
AGPE_s <- variance_histogram(post_survAGPE)

ELRI_s <- variance_histogram(post_survELRI)

ELVI_s <- variance_histogram(post_survELVI)

FESU_s <- variance_histogram(post_survFESU)

LOAR_s <- variance_histogram(post_survLOAR)

POAL_s <- variance_histogram(post_survPOAL)

POSY_s <- variance_histogram(post_survPOSY)

# flowering
AGPE_f <- variance_histogram(post_flwAGPE)

ELRI_f <- variance_histogram(post_flwELRI)

ELVI_f <- variance_histogram(post_flwELVI)

FESU_f <- variance_histogram(post_flwFESU)

LOAR_f <- variance_histogram(post_flwLOAR)

POAL_f <- variance_histogram(post_flwPOAL)

POSY_f <- variance_histogram(post_flwPOSY)

# growth
AGPE_g <- variance_histogram(post_growAGPE)

ELRI_g <- variance_histogram(post_growELRI)

ELVI_g <- variance_histogram(post_growELVI)

FESU_g <- variance_histogram(post_growFESU)

LOAR_g <- variance_histogram(post_growLOAR)

POAL_g <- variance_histogram(post_growPOAL)

POSY_g <- variance_histogram(post_growPOSY)

# fertility

AGPE_fert <- variance_histogram(post_fertAGPE)

ELRI_fert <- variance_histogram(post_fertELRI)

ELVI_fert <- variance_histogram(post_fertELVI)

FESU_fert <- variance_histogram(post_fertFESU)

LOAR_fert <- variance_histogram(post_fertLOAR)

POAL_fert <- variance_histogram(post_fertPOAL)

POSY_fert <- variance_histogram(post_fertPOSY)

# spikelets
# 
# AGPE_spike <- variance_histogram(post_spikeAGPE)
# 
# # ELRI_spike <- variance_histogram(post_spikeELRI)
# # 
# # ELVI_spike <- variance_histogram(post_spikeELVI)
# 
# FESU_spike <- variance_histogram(post_spikeFESU)
# 
# LOAR_spike <- variance_histogram(post_spikeLOAR)
# 
# POAL_spike <- variance_histogram(post_spikePOAL)
# 
# POSY_spike <- variance_histogram(post_spikePOSY)

# seed to seedling

# AGPE_s_to_s <- variance_histogram(post_s_to_sAGPE)
# 
# # ELRI_s_to_s <- variance_histogram(post_s_to_sELRI)
# # 
# # ELVI_s_to_s <- variance_histogram(post_s_to_sELVI)
# 
# FESU_s_to_s <- variance_histogram(post_s_to_sFESU)
# 
# LOAR_s_to_s <- variance_histogram(post_s_to_sLOAR)
# 
# POAL_s_to_s <- variance_histogram(post_s_to_sPOAL)
# 
# POSY_s_to_s <- variance_histogram(post_s_to_sPOSY)


# combining the individual histograms together with grid.arrange and adding labels
survvar <- grid.arrange(AGPE_s, ELRI_s, ELVI_s, FESU_s, LOAR_s, POAL_s, POSY_s,  ncol= 1)
titlesurv <- annotate_figure(survvar, top = "Survival", left = "")
flwrvar <- grid.arrange(AGPE_f, ELRI_f, ELVI_f, FESU_f, LOAR_f, POAL_f, POSY_f, ncol= 1)
titleflw <- annotate_figure(flwrvar, top = "Flowering", left = "")
growvar <- grid.arrange(AGPE_g, ELRI_g, ELVI_g, FESU_g, LOAR_g, POAL_g, POSY_g,  ncol= 1)
titlegrow <- annotate_figure(growvar, top = "Growth", left = "")
fertvar <- grid.arrange(AGPE_fert, ELRI_fert, ELVI_fert, FESU_fert, LOAR_fert, POAL_fert, POSY_fert,  ncol= 1)
titlefert <- annotate_figure(fertvar, top = "Fertility", left = "")
# spikevar <- grid.arrange(AGPE_spike,  FESU_spike, LOAR_spike, POAL_spike, POSY_spike,  ncol= 1)
# titlespike <- annotate_figure(spikevar, top = "Spikelets per Infl.", left = "")
# s_to_svar <- grid.arrange(AGPE_s_to_s,  FESU_s_to_s, LOAR_s_to_s, POAL_s_to_s, POSY_s_to_s,  ncol= 1)
# titles_to_s <- annotate_figure(s_to_svar, top = "Seed to Seedling", left = "")

var <- grid.arrange(titlesurv, titlegrow, titleflw, titlefert, ncol = 5)
titlevar <- annotate_figure(var, top = "Difference in Interannual Variance", left = "Posterior Density")
```

```{r variance histogram plots, echo=FALSE, fig.width = 9, fig.height = 12}
# plotting the combined figure of all the variance estimates by species and by vital rate
# These historgrams can be used indivually as panels for figures with model fits.
titlevar
```

Plots of mean posteriors
```{r mean posterior histogram gg objects, include=FALSE}
# Variance posterior distributions by species
# This function has code to do either two distributions of the variance between e+ and e- or a distribution of the difference between the two
means_histogram <- function(df){
  require(ggplot2)
  spp <- ggplot() +
    geom_histogram(data = df, aes(df$`beta[3]`), fill = "#4d9158", alpha = .6, bins = 200) +
    geom_vline(xintercept = mean(df$`beta[3]`), col = "#4d9158") +
    labs(x = "Mean Endophyte Effect", y = "Posterior density") + theme_classic()
  return(spp)
}
# survival
AGPE_s <- means_histogram(post_survAGPE)

ELRI_s <- means_histogram(post_survELRI)

ELVI_s <- means_histogram(post_survELVI)

FESU_s <- means_histogram(post_survFESU)

LOAR_s <- means_histogram(post_survLOAR)

POAL_s <- means_histogram(post_survPOAL)

POSY_s <- means_histogram(post_survPOSY)

# flowering
AGPE_f <- means_histogram(post_flwAGPE)

ELRI_f <- means_histogram(post_flwELRI)

ELVI_f <- means_histogram(post_flwELVI)

FESU_f <- means_histogram(post_flwFESU)

LOAR_f <- means_histogram(post_flwLOAR)

POAL_f <- means_histogram(post_flwPOAL)

POSY_f <- means_histogram(post_flwPOSY)

# growth
AGPE_g <- means_histogram(post_growAGPE)

ELRI_g <- means_histogram(post_growELRI)

ELVI_g <- means_histogram(post_growELVI)

FESU_g <- means_histogram(post_growFESU)

LOAR_g <- means_histogram(post_growLOAR)

POAL_g <- means_histogram(post_growPOAL)

POSY_g <- means_histogram(post_growPOSY)

# fertility

AGPE_fert <- means_histogram(post_fertAGPE)

ELRI_fert <- means_histogram(post_fertELRI)

ELVI_fert <- means_histogram(post_fertELVI)

FESU_fert <- means_histogram(post_fertFESU)

LOAR_fert <- means_histogram(post_fertLOAR)

POAL_fert <- means_histogram(post_fertPOAL)

POSY_fert <- means_histogram(post_fertPOSY)

# spikelets
# 
# AGPE_spike <- means_histogram(post_spikeAGPE)
# 
# # ELRI_spike <- means_histogram(post_spikeELRI)
# # 
# # ELVI_spike <- means_histogram(post_spikeELVI)
# 
# FESU_spike <- means_histogram(post_spikeFESU)
# 
# LOAR_spike <- means_histogram(post_spikeLOAR)
# 
# POAL_spike <- means_histogram(post_spikePOAL)
# 
# POSY_spike <- means_histogram(post_spikePOSY)

# seed to seedling

# AGPE_s_to_s <- means_histogram(post_s_to_sAGPE)
# 
# # ELRI_s_to_s <- means_histogram(post_s_to_sELRI)
# # 
# # ELVI_s_to_s <- means_histogram(post_s_to_sELVI)
# 
# FESU_s_to_s <- means_histogram(post_s_to_sFESU)
# 
# LOAR_s_to_s <- means_histogram(post_s_to_sLOAR)
# 
# POAL_s_to_s <- means_histogram(post_s_to_sPOAL)
# 
# POSY_s_to_s <- means_histogram(post_s_to_sPOSY)


# combining the individual histograms together with grid.arrange and adding labels
survmean <- grid.arrange(AGPE_s, ELRI_s, ELVI_s, FESU_s, LOAR_s, POAL_s, POSY_s,  ncol= 1)
titlesurv <- annotate_figure(survmean, top = "Survival", left = "")
flwrmean <- grid.arrange(AGPE_f, ELRI_f, ELVI_f, FESU_f, LOAR_f, POAL_f, POSY_f, ncol= 1)
titleflw <- annotate_figure(flwrmean, top = "Flowering", left = "")
growmean <- grid.arrange(AGPE_g, ELRI_g, ELVI_g, FESU_g, LOAR_g, POAL_g, POSY_g,  ncol= 1)
titlegrow <- annotate_figure(growmean, top = "Growth", left = "")
fertmean <- grid.arrange(AGPE_fert, ELRI_fert, ELVI_fert, FESU_fert, LOAR_fert, POAL_fert, POSY_fert,  ncol= 1)
titlefert <- annotate_figure(fertmean, top = "Fertility", left = "")
# spikemean <- grid.arrange(AGPE_spike,  FESU_spike, LOAR_spike, POAL_spike, POSY_spike,  ncol= 1)
# titlespike <- annotate_figure(spikemean, top = "Spikelets per Infl.", left = "")
# s_to_smean <- grid.arrange(AGPE_s_to_s,  FESU_s_to_s, LOAR_s_to_s, POAL_s_to_s, POSY_s_to_s,  ncol= 1)
# titles_to_s <- annotate_figure(s_to_smean, top = "Seed to Seedling", left = "")

means <- grid.arrange(titlesurv, titlegrow, titleflw, titlefert, ncol = 5)
titlemeans <- annotate_figure(means, top = "Difference in Interannual Variance", left = "Posterior Density")
```

```{r mean histogram plots, echo=FALSE, fig.width = 9, fig.height = 12}
# plotting the combined figure of all the mean estimates by species and by vital rate
# These historgrams can be used indivually as panels for figures with model fits.
titlemeans
```

```{r caterpiller plot of endo effects on mean and variance}
# calc mean and 80% CI and calc for each vital rate.
getmean <- function(post, species = "", vr = ""){
post_mean <- post %>% 
  dplyr::select(`beta[3]`, `sigma_e[1]`, `sigma_e[2]`) %>%
  mutate(diff_sigma = `sigma_e[1]` - `sigma_e[2]`) %>% 
  mutate(species = species, vitalrate = vr) %>% 
  melt() %>% 
  group_by(species, vitalrate, variable) %>% 
  summarize(mean = mean(value),
            lowCI = quantile(value, prob = c(.1)),
            highCI = quantile(value, prob = c(.9)))
return(post_mean)
}

s <- list(post_survAGPE = post_survAGPE,post_survELRI = post_survELRI, post_survELVI = post_survELVI,post_survFESU = post_survFESU, post_survLOAR = post_survLOAR, post_survPOAL = post_survPOAL,post_survPOSY = post_survPOSY)
surv <- lapply(seq_along(s),FUN = function(i) getmean(s[[i]], species = str_sub(names(s)[[i]], -4), vr = "Survival"))
survdf <- bind_rows(surv)

s <- list(post_growAGPE = post_growAGPE,post_growELRI = post_growELRI, post_growELVI = post_growELVI,post_growFESU = post_growFESU, post_growLOAR = post_growLOAR, post_growPOAL = post_growPOAL,post_growPOSY = post_growPOSY)
grow <- lapply(seq_along(s),FUN = function(i) getmean(s[[i]], species = str_sub(names(s)[[i]], -4), vr = "Growth"))
growdf <- bind_rows(grow)

s <- list(post_flwAGPE = post_flwAGPE,post_flwELRI = post_flwELRI, post_flwELVI = post_flwELVI,post_flwFESU = post_flwFESU, post_flwLOAR = post_flwLOAR, post_flwPOAL = post_flwPOAL,post_flwPOSY = post_flwPOSY)
flw <- lapply(seq_along(s),FUN = function(i) getmean(s[[i]], species = str_sub(names(s)[[i]], -4), vr = "Flowering"))
flwdf <- bind_rows(flw)

s <- list(post_fertAGPE = post_fertAGPE,post_fertELRI = post_fertELRI, post_fertELVI = post_fertELVI,post_fertFESU = post_fertFESU, post_fertLOAR = post_fertLOAR, post_fertPOAL = post_fertPOAL,post_fertPOSY = post_fertPOSY)
fert <- lapply(seq_along(s),FUN = function(i) getmean(s[[i]], species = str_sub(names(s)[[i]], -4), vr = "Fertility"))
fertdf <- bind_rows(fert)

s <- list(post_spikeAGPE = post_spikeAGPE,post_spikeELRI = post_spikeELRI, post_spikeELVI = post_spikeELVI,post_spikeFESU = post_spikeFESU, post_spikeLOAR = post_spikeLOAR, post_spikePOAL = post_spikePOAL,post_spikePOSY = post_spikePOSY)
spike <- lapply(seq_along(s),FUN = function(i) getmean(s[[i]], species = str_sub(names(s)[[i]], -4), vr = "Spikelets"))
spikedf <- bind_rows(spike)

# Merge the diff. vital rates summaries into one df
vrdf <- bind_rows(survdf,growdf, flwdf, fertdf, spikedf) %>% 
  mutate(variable = recode(variable, "beta[3]" = "Mean Endophyte Effect",
                                     "diff_sigma" = "Difference in SD",
                                     "sigma_e[1]" = "E Minus sd",
                                     "sigma_e[2]" = "E Plus sd")) %>% 
  filter(variable == "Mean Endophyte Effect")

CatPlot <- ggplot(data = vrdf, aes(x = fct_reorder(species, lowCI),
                                   y = mean,
                                   ymin = lowCI, 
                                   ymax = highCI,
                                   col = vitalrate,
                                   shape = vitalrate)) +
                    geom_pointrange(size = 1.0) +  
                    facet_grid(rows = vars(vitalrate), cols = vars(variable)) +
                    geom_hline(yintercept = 0, linetype = "dotted") +
                    xlab("Species\n") + ylab("\nCoefficient Estimate (w/ 80% CI)") +
                    coord_flip() +
                    theme_classic(base_size = 30) + theme(axis.title = element_text(size = 50), axis.text = element_text(size = 25)) 

```

```{r caterpillar plot, echo=FALSE, fig.width = 10, fig.height = 6}
# plotting the combined figure of all the mean estimates by species and by vital rate
# These historgrams can be used indivually as panels for figures with model fits.
CatPlot
```

Plots of model fits with data
```{r observed survival bins, include=FALSE}
# Function to bin the observed survival data according to endophyte status and size classes for plotting against the fitted model
surv_data_bins <- function(df_raw){
  require(tidyverse)
  df_raw <- ungroup(df_raw)
  surv_bin_minus <- df_raw %>% 
    dplyr::select(surv_t1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 0) %>%
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by( size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
            mean_surv = mean(surv_t1,na.rm=T),
            samplesize = n())
  
  surv_bin_plus <- df_raw %>%
    dplyr::select(surv_t1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 1) %>%
    rename(Endo = endo_01) %>%
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>%
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>%
    group_by(size_bin, Year) %>%
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_surv = mean(surv_t1,na.rm=T),
              samplesize = n())

  surv_bin_byyear <- df_raw %>%
    dplyr::select(surv_t1, logsize_t, year_t, endo_01) %>%
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>%
    rename(Endo = endo_01) %>%
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>%
    group_by(size_bin, Year, Endo) %>%
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_surv = mean(surv_t1,na.rm=T),
              samplesize = n())

  surv_bin_mean <- df_raw %>%
    dplyr::select(surv_t1, logsize_t, endo_01) %>%
    mutate(Endo = recode(endo_01, "0" = "E-", "1" = "E+")) %>%
    mutate(size_bin = cut_interval(logsize_t, n = 12)) %>%
    group_by(size_bin, Endo) %>%
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_surv = mean(surv_t1,na.rm=T),
              samplesize = n())
  
  surv_bins_list <- list(surv_bin_minus, surv_bin_plus, surv_bin_byyear, surv_bin_mean)
  names(surv_bins_list) <- c("surv_bins_minus", "surv_bins_plus", "surv_bin_byyear", "surv_bin_mean")
  return(surv_bins_list)
}

AGPEsurv_bins <- surv_data_bins(AGPE_surv_data)

ELRIsurv_bins <- surv_data_bins(ELRI_surv_data)

ELVIsurv_bins <- surv_data_bins(ELVI_surv_data)

FESUsurv_bins <- surv_data_bins(FESU_surv_data)

LOARsurv_bins <- surv_data_bins(LOAR_surv_data)

POALsurv_bins <- surv_data_bins(POAL_surv_data)

POSYsurv_bins <- surv_data_bins(POSY_surv_data)
```

```{r observed flowering bins, include=FALSE}
# Function to bin the observed flowering data according to endophyte status and size classes for plotting against the fitted model
flw_data_bins <- function(df_raw){
  require(tidyverse)
  df_raw <- ungroup(df_raw)
  flw_bin_minus <- df_raw %>% 
    dplyr::select(FLW_STAT_T1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 0) %>% 
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_flw = mean(FLW_STAT_T1,na.rm=T),
              samplesize = n())

  flw_bin_plus <- df_raw %>% 
    dplyr::select(FLW_STAT_T1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 1) %>% 
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_flw = mean(FLW_STAT_T1,na.rm=T),
              samplesize = n())
  
  flw_bin_byyear <- df_raw %>% 
    dplyr::select(FLW_STAT_T1, logsize_t, year_t, endo_01) %>%
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year, Endo) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_flw = mean(FLW_STAT_T1,na.rm=T),
              samplesize = n())


  flw_bin_mean <- df_raw %>% 
    dplyr::select(FLW_STAT_T1, logsize_t, endo_01) %>%
    mutate(Endo = recode(endo_01, "0" = "E-", "1" = "E+", minus = 'E-', plus = 'E+')) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 12)) %>% 
    group_by(size_bin, endo_01) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_flw = mean(FLW_STAT_T1,na.rm=T),
              samplesize = n())
  flw_bins_list <- list(flw_bin_minus, flw_bin_plus, flw_bin_byyear, flw_bin_mean)
  names(flw_bins_list) <- c("flw_bins_minus", "flw_bins_plus", "flw_bin_byyear", "flw_bin_mean")

  return(flw_bins_list)
}

AGPEflw_bins <- flw_data_bins(AGPE_flw_data)

ELRIflw_bins <- flw_data_bins(ELRI_flw_data)

ELVIflw_bins <- flw_data_bins(ELVI_flw_data)

FESUflw_bins <- flw_data_bins(FESU_flw_data)

LOARflw_bins <- flw_data_bins(LOAR_flw_data)

POALflw_bins <- flw_data_bins(POAL_flw_data)

POSYflw_bins <- flw_data_bins(POSY_flw_data)
```

```{r observed growth bins, include=FALSE}
# Function to bin the observed growth data according to endophyte status and size classes for plotting against the fitted model
grow_data_bins <- function(df_raw){
  require(tidyverse)
  df_raw <- ungroup(df_raw)
  grow_bin_minus<- df_raw %>% 
    dplyr::select(size_t1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 0) %>%     
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_grow = mean(size_t1,na.rm=T),
              samplesize = n())
  
  grow_bin_plus <- df_raw %>% 
    dplyr::select(size_t1, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 1) %>% 
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_grow = mean(size_t1,na.rm=T),
              samplesize = n())
  
  grow_bin_byyear <- df_raw %>% 
    dplyr::select(size_t1, logsize_t, year_t, endo_01) %>%
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year, endo_01) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_grow = mean(size_t1,na.rm=T),
              samplesize = n())
  
  grow_binmean <- df_raw %>% 
    dplyr::select(size_t1, logsize_t, endo_01) %>%
    mutate(endo_01 = as.character(endo_01)) %>%
    mutate(Endo = recode(endo_01, "0" = "E-", "1" = "E+")) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 12)) %>% 
    group_by(size_bin, Endo) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_grow = mean(size_t1,na.rm=T),
              samplesize = n())

  grow_bins_list <- list(grow_bin_minus, grow_bin_plus, grow_bin_byyear, grow_binmean)
  names(grow_bins_list) <- c("grow_bins_minus", "grow_bins_plus", "grow_bin_byyear", "grow_bin_mean")
  return(grow_bins_list)
}

AGPEgrow_bins <- grow_data_bins(AGPE_grow_data)

ELRIgrow_bins <- grow_data_bins(ELRI_grow_data)

ELVIgrow_bins <- grow_data_bins(ELVI_grow_data)

FESUgrow_bins <- grow_data_bins(FESU_grow_data)

LOARgrow_bins <- grow_data_bins(LOAR_grow_data)

POALgrow_bins <- grow_data_bins(POAL_grow_data)

POSYgrow_bins <- grow_data_bins(POSY_grow_data)
```


```{r observed fertility bins, include=FALSE}
# Function to bin the observed growth data according to endophyte status and size classes for plotting against the fitted model
fert_data_bins <- function(df_raw){
  require(tidyverse)
  df_raw <- ungroup(df_raw)
  fert_bin_minus<- df_raw %>% 
    dplyr::select(FLW_COUNT_T, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 0) %>% 
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_fert = mean(FLW_COUNT_T,na.rm=T),
              samplesize = n())
  
  fert_bin_plus <- df_raw %>% 
    dplyr::select(FLW_COUNT_T, logsize_t, year_t, endo_01) %>%
    filter(endo_01 == 1) %>% 
    rename(Endo = endo_01) %>% 
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_fert = mean(FLW_COUNT_T,na.rm=T),
              samplesize = n())
  
  fert_bin_byyear <- df_raw %>% 
    dplyr::select(FLW_COUNT_T, logsize_t, year_t, endo_01) %>%
    mutate(Year = as.factor(as.integer(as.factor(year_t)))) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 15)) %>% 
    group_by(size_bin, Year, endo_01) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_fert = mean(FLW_COUNT_T,na.rm=T),
              samplesize = n())
  
  fert_binmean <- df_raw %>% 
    dplyr::select(FLW_COUNT_T, logsize_t, endo_01) %>%
    mutate(endo_01 = as.character(endo_01)) %>% 
    rename(Endo = endo_01) %>% 
    mutate(size_bin = cut_interval(logsize_t, n = 12)) %>% 
    group_by(size_bin, Endo) %>% 
    summarise(mean_size = mean((logsize_t),na.rm=T),
              mean_fert = mean(FLW_COUNT_T,na.rm=T),
              samplesize = n())

  fert_bins_list <- list(fert_bin_minus, fert_bin_plus, fert_bin_byyear, fert_binmean)
  return(fert_bins_list)
}

AGPEfert_bins <- fert_data_bins(AGPE_fert_data)

ELRIfert_bins <- fert_data_bins(ELRI_fert_data)

ELVIfert_bins <- fert_data_bins(ELVI_fert_data)

FESUfert_bins <- fert_data_bins(FESU_fert_data)

LOARfert_bins <- fert_data_bins(LOAR_fert_data)

POALfert_bins <- fert_data_bins(POAL_fert_data)

POSYfert_bins <- fert_data_bins(POSY_fert_data)
```



```{r survival fits, include=FALSE}
# function to generate the mean, and year and plot specific survival model fits and store for plotting
surv_fits <- function(df_raw, df_samples){
  require(tidyverse)

  nvalues <- length(df_raw$logsize_t)
  xdummy <- seq(min(df_raw$logsize_t), max(df_raw$logsize_t), length.out = nvalues)

  #endophyte negative fits  
  ydummy_eminus <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01)))
  ydummy_eminus_y1 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'tau_year[1,1]')))
  ydummy_eminus_y2 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'tau_year[1,2]')))
  ydummy_eminus_y3 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + + mean(df_samples$'beta[3]')*0  + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,3]')))
  ydummy_eminus_y4 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,4]'))) 
  ydummy_eminus_y5 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,5]')))
  ydummy_eminus_y6 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,6]')))
  ydummy_eminus_y7 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,7]')))
  ydummy_eminus_y8 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,8]')))
  ydummy_eminus_y9 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,9]')))
  ydummy_eminus_y10 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,10]')))
  ydummy_eminus_y11 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[1,11]')))

    meanminussamps<- matrix(nrow = length(xdummy), ncol = 10000)
  for(i in 1:10000){
    meanminussamps[,i] <- invlogit(sample(df_samples$'beta[1]', size = 1) + sample(df_samples$'beta[2]', size = 1)*xdummy + sample(df_samples$'beta[3]', size = 1)*0 + sample(df_samples$'beta[4]', size = 1)*mean(df_raw$origin_01))
}
 
  meanminusCI <- as.data.frame(t(apply(meanminussamps,1, quantile, prob = c(.1,.9)))) %>% 
    rename(lower ='10%', upper = '90%') 

 meanminus500samps <- as.data.frame(meanminussamps[,sample(ncol(meanminussamps), 500)]) %>% 
   cbind(xdummy)
  
      
  # endophyte positive fits
  ydummy_eplus <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01)))
  ydummy_eplus_y1 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,1]')))
  ydummy_eplus_y2 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,2]')))
  ydummy_eplus_y3 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + + mean(df_samples$'beta[3]')*1  + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,3]')))
  ydummy_eplus_y4 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,4]'))) 
  ydummy_eplus_y5 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,5]')))
  ydummy_eplus_y6 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,6]')))
  ydummy_eplus_y7 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,7]')))
  ydummy_eplus_y8 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,8]')))
  ydummy_eplus_y9 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,9]')))
  ydummy_eplus_y10 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,10]')))
  ydummy_eplus_y11 <- as.vector(invlogit(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) +  mean(df_samples$'tau_year[2,11]')))

    meanplussamps<- matrix(nrow = length(xdummy), ncol = 10000)
  for(i in 1:10000){
    meanplussamps[,i] <- invlogit(sample(df_samples$'beta[1]', size = 1) + sample(df_samples$'beta[2]', size = 1)*xdummy + sample(df_samples$'beta[3]', size = 1)*1 + sample(df_samples$'beta[4]', size = 1)*mean(df_raw$origin_01))
}
 
  meanplusCI <- as.data.frame(t(apply(meanplussamps,1, quantile, prob = c(.1,.9)))) %>% 
    rename(lower ='10%', upper = '90%') 


  eminus <- list(ydummy_eminus, ydummy_eminus_y1, ydummy_eminus_y2, ydummy_eminus_y3, ydummy_eminus_y4, ydummy_eminus_y5, ydummy_eminus_y6, ydummy_eminus_y7, ydummy_eminus_y8, ydummy_eminus_y9, ydummy_eminus_y10, ydummy_eminus_y11, meanminusCI)
  names(eminus) <- c("mean", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", "y11", "CI")
  
  eplus <- list(ydummy_eplus, ydummy_eplus_y1, ydummy_eplus_y2, ydummy_eplus_y3, ydummy_eplus_y4, ydummy_eplus_y5, ydummy_eplus_y6, ydummy_eplus_y7, ydummy_eplus_y8, ydummy_eplus_y9, ydummy_eplus_y10, ydummy_eplus_y11, meanplusCI)
  names(eplus) <- c("mean", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", "y11", "CI")  
  

  
  surv_fits_list <- list(eminus, eplus, xdummy)
  names(surv_fits_list) <- c("eminus", "eplus", "xdummy")
  return(surv_fits_list)
}

AGPEsurv_fits <- surv_fits(AGPE_surv_data, post_survAGPE)

ELRIsurv_fits <- surv_fits(ELRI_surv_data, post_survELRI)

ELVIsurv_fits <- surv_fits(ELVI_surv_data, post_survELVI)

FESUsurv_fits <- surv_fits(FESU_surv_data, post_survFESU)

LOARsurv_fits <- surv_fits(LOAR_surv_data, post_survLOAR)

POALsurv_fits <- surv_fits(POAL_surv_data, post_survPOAL)

POSYsurv_fits <- surv_fits(POSY_surv_data, post_survPOSY)

```

```{r flowering fits, include=FALSE}
# function to generate the mean, and year and plot specific flowering model fits and store for plotting
flw_fits <- function(df_raw, df_samples){
  require(tidyverse)

  nvalues <- length(df_raw$logsize_t)
  xdummy <- seq(min(df_raw$logsize_t), max(df_raw$logsize_t), length.out = nvalues)


}
```

```{r growth fits, include=FALSE}
# function to generate the mean, and year and plot specific growth model fits and store for plotting
grow_fits <- function(df_raw, df_samples){
  require(tidyverse)

  nvalues <- length(df_raw$logsize_t)
  xdummy <- seq(min(df_raw$logsize_t), max(df_raw$logsize_t), length.out = nvalues)

  #endophyte negative fits  
  ydummy_eminus <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0))
  ydummy_eminus_y1 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,1]')))
  ydummy_eminus_y2 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,2]')))
  ydummy_eminus_y3 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + + mean(df_samples$'beta[3]')*0  + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,3]')))
  ydummy_eminus_y4 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,4]'))) 
  ydummy_eminus_y5 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,5]')))
  ydummy_eminus_y6 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,6]')))
  ydummy_eminus_y7 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,7]')))
  ydummy_eminus_y8 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,8]')))
  ydummy_eminus_y9 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,9]')))
  ydummy_eminus_y10 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,10]')))
  ydummy_eminus_y11 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*0 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*0 + mean(df_samples$'tau_year[1,11]')))

    meanminussamps<- matrix(nrow = length(xdummy), ncol = 10000)
  for(i in 1:10000){
    meanminussamps[,i] <- exp(sample(df_samples$'beta[1]', size = 1) + sample(df_samples$'beta[2]', size = 1)*xdummy + sample(df_samples$'beta[3]', size = 1)*0 + sample(df_samples$'beta[4]', size = 1)*mean(df_raw$origin_01) + sample(df_samples$'beta[5]', size = 1)*xdummy*0)
}
 
  meanminusCI <- as.data.frame(t(apply(meanminussamps,1, quantile, prob = c(.1,.9)))) %>% 
    rename(lower ='10%', upper = '90%') 


  
      
  # endophyte positive fits
  ydummy_eplus <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1))
  ydummy_eplus_y1 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,1]')))
  ydummy_eplus_y2 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,2]')))
  ydummy_eplus_y3 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + + mean(df_samples$'beta[3]')*1  + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,3]')))
  ydummy_eplus_y4 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,4]'))) 
  ydummy_eplus_y5 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,5]')))
  ydummy_eplus_y6 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,6]')))
  ydummy_eplus_y7 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,7]')))
  ydummy_eplus_y8 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,8]')))
  ydummy_eplus_y9 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,9]')))
  ydummy_eplus_y10 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,10]')))
  ydummy_eplus_y11 <- as.vector(exp(mean(df_samples$'beta[1]') + mean(df_samples$'beta[2]')*xdummy + mean(df_samples$'beta[3]')*1 + mean(df_samples$'beta[4]')*mean(df_raw$origin_01) + mean(df_samples$'beta[5]')*xdummy*1 + mean(df_samples$'tau_year[2,11]')))

    meanplussamps<- matrix(nrow = length(xdummy), ncol = 10000)
  for(i in 1:10000){
    meanplussamps[,i] <- exp(sample(df_samples$'beta[1]', size = 1) + sample(df_samples$'beta[2]', size = 1)*xdummy + sample(df_samples$'beta[3]', size = 1)*1 + sample(df_samples$'beta[4]', size = 1)*mean(df_raw$origin_01) + sample(df_samples$'beta[5]', size = 1)*xdummy*1)
}
 
  meanplusCI <- as.data.frame(t(apply(meanplussamps,1, quantile, prob = c(.1,.9)))) %>% 
    rename(lower ='10%', upper = '90%') 



  eminus <- list(ydummy_eminus, ydummy_eminus_y1, ydummy_eminus_y2, ydummy_eminus_y3, ydummy_eminus_y4, ydummy_eminus_y5, ydummy_eminus_y6, ydummy_eminus_y7, ydummy_eminus_y8, ydummy_eminus_y9, ydummy_eminus_y10, ydummy_eminus_y11, meanminusCI)
  names(eminus) <- c("mean", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", "y11", "CI")
  
  eplus <- list(ydummy_eplus, ydummy_eplus_y1, ydummy_eplus_y2, ydummy_eplus_y3, ydummy_eplus_y4, ydummy_eplus_y5, ydummy_eplus_y6, ydummy_eplus_y7, ydummy_eplus_y8, ydummy_eplus_y9, ydummy_eplus_y10, ydummy_eplus_y11, meanplusCI)
  names(eplus) <- c("mean", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", "y11", "CI")  
  

  
  grow_fits_list <- list(eminus, eplus, xdummy)
  names(grow_fits_list) <- c("eminus", "eplus", "xdummy")
  return(grow_fits_list)
}

AGPEgrow_fits <- grow_fits(AGPE_grow_data, post_growAGPE)

ELRIgrow_fits <- grow_fits(ELRI_grow_data, post_growELRI)

ELVIgrow_fits <- grow_fits(ELVI_grow_data, post_growELVI)

FESUgrow_fits <- grow_fits(FESU_grow_data, post_growFESU)

LOARgrow_fits <- grow_fits(LOAR_grow_data, post_growLOAR)

POALgrow_fits <- grow_fits(POAL_grow_data, post_growPOAL)

POSYgrow_fits <- grow_fits(POSY_grow_data, post_growPOSY)

```

```{r fertility fits, include=FALSE}
# function to generate the mean, and year and plot specific fertility model fits and store for plotting
fert_fits <- function(df_raw, df_samples){
  require(tidyverse)
  
  nvalues <- length(df_raw$logsize_t)
  xdummy <- seq(min(df_raw$logsize_t), max(df_raw$logsize_t), length.out = nvalues)


}
```


```{r survival raw and fits ggobjects, include = FALSE}
# Putting together the raw, binned data and the fitted models so that they can be visualized together.
surv_minus_byyear <- function(fits, bins, title){
  require(ggplot2)
  fits_df <- as.data.frame(fits)
  fits_df <- melt(fits_df, id = "xdummy",
                      measure.vars = c("eminus.y1","eminus.y2", 
                                       "eminus.y3", "eminus.y4", 
                                       "eminus.y5", "eminus.y6", 
                                       "eminus.y7", "eminus.y8", 
                                       "eminus.y9", "eminus.y10",
                                       "eminus.y11")) %>% 
  mutate(Year = recode(variable, "eminus.y1" = '1',"eminus.y2" = "2", 
                       "eminus.y3" = "3", "eminus.y4" = "4", 
                       "eminus.y5" = "5", "eminus.y6" = "6", 
                       "eminus.y7" = "7", "eminus.y8" = "8", 
                       "eminus.y9" = "9", "eminus.y10" = "10",
                       "eminus.y11" = "11")) 
  bins_df <- as.data.frame(bins[["surv_bins_minus"]])
  Eminusbyyear <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = value, color = Year),  lwd = 2) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_surv, color = Year, lwd = samplesize)) +  
  labs(title = title, subtitle = "E-", x = "log(size_t)", y = "Prob. of Survival") +
  scale_color_manual(values = yearcolors) + guides(lwd = "none") + theme_classic() +           
  theme(axis.title = element_text(size = 30), axis.text = element_text(size = 30),
        legend.title = element_text(size = 30), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=8)))

return(Eminusbyyear)  
}
surv_plus_byyear <- function(fits, bins, title){
  require(ggplot2)
  fits_df <- as.data.frame(fits)
    fits_df <- melt(fits_df, id = "xdummy",
                      measure.vars = c("eplus.y1","eplus.y2", 
                                       "eplus.y3", "eplus.y4", 
                                       "eplus.y5", "eplus.y6", 
                                       "eplus.y7", "eplus.y8", 
                                       "eplus.y9", "eplus.y10",
                                       "eplus.y11")) %>% 
  mutate(Year = recode(variable, "eplus.y1" = '1',"eplus.y2" = "2", 
                       "eplus.y3" = "3", "eplus.y4" = "4", 
                       "eplus.y5" = "5", "eplus.y6" = "6", 
                       "eplus.y7" = "7", "eplus.y8" = "8", 
                       "eplus.y9" = "9", "eplus.y10" = "10",
                       "eplus.y11" = "11")) 
  bins_df <- as.data.frame(bins[["surv_bins_plus"]])
  Eplusbyyear <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = value, color = Year), lwd = 2) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_surv, color = Year, lwd = samplesize)) +  
  labs(title = title, subtitle = "E+", x = "log(size_t)", y = "Prob. of Survival") +
  scale_color_manual(values = yearcolors) + guides(lwd = "none") +theme_classic() +
  theme(axis.title = element_text(size = 30), axis.text = element_text(size = 30),
        legend.title = element_text(size = 30), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=8)))

return(Eplusbyyear)  
}
surv_mean <- function(fits, bins, title){
fits_df <- as.data.frame(fits)
bins_df <- as.data.frame(bins[["surv_bin_mean"]])
survmean <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = eplus.mean), color = "#6a3d9a", lwd = 2)+
  geom_line(aes(x = xdummy, y = eminus.mean), color = "#ff7f00", lwd = 2) +
  geom_ribbon(aes(x = xdummy, ymin = eplus.CI.lower, ymax = eplus.CI.upper), fill = "#6a3d9a", alpha = .3) +
  geom_ribbon(aes(x = xdummy, ymin = eminus.CI.lower, ymax = eminus.CI.upper), fill = "#ff7f00", alpha = .3) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_surv, color = Endo, lwd = samplesize)) +
  labs(title = title, subtitle = "Mean Survival Probability", x = "log(size_t)", y = "Prob. of Survival") +
  scale_color_manual(values = colors2) + guides(lwd = "none") + theme_classic() +
  theme(axis.title = element_text(size = 30), axis.text = element_text(size = 30),
        legend.title = element_text(size = 30), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=8)))
return(survmean)
}

AGPEsurv_minus_byyear <- surv_minus_byyear(AGPEsurv_fits, AGPEsurv_bins, title = "AGPE")
AGPEsurv_plus_byyear <- surv_plus_byyear(AGPEsurv_fits, AGPEsurv_bins, title = "AGPE")
AGPEsurv_mean <- surv_mean(AGPEsurv_fits, AGPEsurv_bins, title = "AGPE")

ELRIsurv_minus_byyear <- surv_minus_byyear(ELRIsurv_fits, ELRIsurv_bins, title = "ELRI")
ELRIsurv_plus_byyear <- surv_plus_byyear(ELRIsurv_fits, ELRIsurv_bins, title = "ELRI")
ELRIsurv_mean <- surv_mean(ELRIsurv_fits, ELRIsurv_bins, title = "ELRI")

ELVIsurv_minus_byyear <- surv_minus_byyear(ELVIsurv_fits, ELVIsurv_bins, title = "ELVI")
ELVIsurv_plus_byyear <- surv_plus_byyear(ELVIsurv_fits, ELVIsurv_bins, title = "ELVI")
ELVIsurv_mean <- surv_mean(ELVIsurv_fits, ELVIsurv_bins, title = "ELVI")

FESUsurv_minus_byyear <- surv_minus_byyear(FESUsurv_fits, FESUsurv_bins, title = "FESU")
FESUsurv_plus_byyear <- surv_plus_byyear(FESUsurv_fits, FESUsurv_bins, title = "FESU")
FESUsurv_mean <- surv_mean(FESUsurv_fits, FESUsurv_bins, title = "FESU")

LOARsurv_minus_byyear <- surv_minus_byyear(LOARsurv_fits, LOARsurv_bins, title = "LOAR")
LOARsurv_plus_byyear <- surv_plus_byyear(LOARsurv_fits, LOARsurv_bins, title = "LOAR")
LOARsurv_mean <- surv_mean(LOARsurv_fits, LOARsurv_bins, title = "LOAR")

POALsurv_minus_byyear <- surv_minus_byyear(POALsurv_fits, POALsurv_bins, title = "POAL")
POALsurv_plus_byyear <- surv_plus_byyear(POALsurv_fits, POALsurv_bins, title = "POAL")
POALsurv_mean <- surv_mean(POALsurv_fits, POALsurv_bins, title = "POAL")

POSYsurv_minus_byyear <- surv_minus_byyear(POSYsurv_fits, POSYsurv_bins, title = "POSY")
POSYsurv_plus_byyear <- surv_plus_byyear(POSYsurv_fits, POSYsurv_bins, title = "POSY")
POSYsurv_mean <- surv_mean(POSYsurv_fits, POSYsurv_bins, title = "POSY")

```

```{r survival raw and fits plot annotations, include = FALSE}
survmean <- grid.arrange(AGPEsurv_mean, ELRIsurv_mean, ELVIsurv_mean, FESUsurv_mean, LOARsurv_mean, POALsurv_mean, POSYsurv_mean, ncol = 1)
titlesurvmean <- annotate_figure(survmean, top = "Mean Survival", left = "")

survminus <- grid.arrange(AGPEsurv_minus_byyear, ELRIsurv_minus_byyear, ELVIsurv_minus_byyear, FESUsurv_minus_byyear, LOARsurv_minus_byyear, POALsurv_minus_byyear, POSYsurv_minus_byyear, ncol = 1)
titlesurvminus <- annotate_figure(survminus, top = "E- Survival by Year", left = "")

survplus <- grid.arrange(AGPEsurv_plus_byyear, ELRIsurv_plus_byyear, ELVIsurv_plus_byyear, FESUsurv_plus_byyear, LOARsurv_plus_byyear, POALsurv_plus_byyear, POSYsurv_plus_byyear, ncol = 1)
titlesurvplus <- annotate_figure(survplus, top = "E+ Survival by Year", left = "")

survivalfits <- grid.arrange(titlesurvmean, titlesurvminus, titlesurvplus, ncol = 3)
titlesurvivalfits <- annotate_figure(survivalfits, top = "Survival", left = "")

```

```{r survival figures, echo=FALSE, fig.width = 4, fig.height = 4}
# titlesurvivalfits

FESUsurv_mean
FESUsurv_minus_byyear
FESUsurv_plus_byyear

POSYsurv_mean
POSYsurv_minus_byyear
POSYsurv_plus_byyear
```

```{r growth raw and fits ggobjects, include = FALSE}
# Putting together the raw, binned data and the fitted models so that they can be visualized together.
grow_minus_byyear <- function(fits, bins, title){
  require(ggplot2)
  fits_df <- as.data.frame(fits)
  fits_df <- melt(fits_df, id = "xdummy",
                      measure.vars = c("eminus.y1","eminus.y2", 
                                       "eminus.y3", "eminus.y4", 
                                       "eminus.y5", "eminus.y6", 
                                       "eminus.y7", "eminus.y8", 
                                       "eminus.y9", "eminus.y10",
                                       "eminus.y11")) %>% 
  mutate(Year = recode(variable, "eminus.y1" = '1',"eminus.y2" = "2", 
                       "eminus.y3" = "3", "eminus.y4" = "4", 
                       "eminus.y5" = "5", "eminus.y6" = "6", 
                       "eminus.y7" = "7", "eminus.y8" = "8", 
                       "eminus.y9" = "9", "eminus.y10" = "10",
                       "eminus.y11" = "11")) 
  bins_df <- as.data.frame(bins[["grow_bins_minus"]])
  Eminusbyyear <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = value, color = Year),  lwd = 2) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_grow, color = Year, size = samplesize*60)) +  
  labs(title = title, subtitle = "E-", x = "log(size_t)", y = "log(size_t1)") +
  scale_color_manual(values = yearcolors) + guides(lwd = "none") + theme_classic() +
  theme(axis.title = element_text(size = 60), axis.text = element_text(size = 30),
        legend.title = element_text(size = 40), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=5)))
return(Eminusbyyear)  
}
grow_plus_byyear <- function(fits, bins, title){
  require(ggplot2)
  fits_df <- as.data.frame(fits)
    fits_df <- melt(fits_df, id = "xdummy",
                      measure.vars = c("eplus.y1","eplus.y2", 
                                       "eplus.y3", "eplus.y4", 
                                       "eplus.y5", "eplus.y6", 
                                       "eplus.y7", "eplus.y8", 
                                       "eplus.y9", "eplus.y10",
                                       "eplus.y11")) %>% 
  mutate(Year = recode(variable, "eplus.y1" = '1',"eplus.y2" = "2", 
                       "eplus.y3" = "3", "eplus.y4" = "4", 
                       "eplus.y5" = "5", "eplus.y6" = "6", 
                       "eplus.y7" = "7", "eplus.y8" = "8", 
                       "eplus.y9" = "9", "eplus.y10" = "10",
                       "eplus.y11" = "11")) 
  bins_df <- as.data.frame(bins[["grow_bins_plus"]])
  Eplusbyyear <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = value, color = Year), lwd = 2) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_grow, color = Year, size = samplesize*60)) +  
  labs(title = title, subtitle = "E+", x = "log(size_t)", y = "log(size_t1)") +
  scale_color_manual(values = yearcolors) + guides(lwd = "none") +theme_classic() +
  theme(axis.title = element_text(size = 60), axis.text = element_text(size = 30),
        legend.title = element_text(size = 40), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=5)))
return(Eplusbyyear)  
}
grow_mean <- function(fits, bins, title){
fits_df <- as.data.frame(fits)
bins_df <- as.data.frame(bins[["grow_bin_mean"]])
growmean <- ggplot(data = fits_df) +
  geom_line(aes(x = xdummy, y = eplus.mean), color = "#6a3d9a", lwd = 2)+
  geom_line(aes(x = xdummy, y = eminus.mean), color = "#ff7f00", lwd = 2) +
  geom_ribbon(aes(x = xdummy, ymin = eplus.CI.lower, ymax = eplus.CI.upper), fill = "#6a3d9a", alpha = .3) +
  geom_ribbon(aes(x = xdummy, ymin = eminus.CI.lower, ymax = eminus.CI.upper), fill = "#ff7f00", alpha = .3) +
  geom_point(data = bins_df, aes(x = mean_size, y = mean_grow, color = Endo, size = samplesize*60)) +
  labs(title = title, subtitle = "Mean growth Probability", x = "log(size_t)", y = "log(size_t1)") +
  scale_color_manual(values = colors2) + guides(lwd = "none") + theme_classic() +
  theme(axis.title = element_text(size = 60), axis.text = element_text(size = 30),
        legend.title = element_text(size = 40), legend.text = element_text(size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=10)))
return(growmean)
}

AGPEgrow_minus_byyear <- grow_minus_byyear(AGPEgrow_fits, AGPEgrow_bins, title = "AGPE")
AGPEgrow_plus_byyear <- grow_plus_byyear(AGPEgrow_fits, AGPEgrow_bins, title = "AGPE")
AGPEgrow_mean <- grow_mean(AGPEgrow_fits, AGPEgrow_bins, title = "AGPE")

ELRIgrow_minus_byyear <- grow_minus_byyear(ELRIgrow_fits, ELRIgrow_bins, title = "ELRI")
ELRIgrow_plus_byyear <- grow_plus_byyear(ELRIgrow_fits, ELRIgrow_bins, title = "ELRI")
ELRIgrow_mean <- grow_mean(ELRIgrow_fits, ELRIgrow_bins, title = "ELRI")

ELVIgrow_minus_byyear <- grow_minus_byyear(ELVIgrow_fits, ELVIgrow_bins, title = "ELVI")
ELVIgrow_plus_byyear <- grow_plus_byyear(ELVIgrow_fits, ELVIgrow_bins, title = "ELVI")
ELVIgrow_mean <- grow_mean(ELVIgrow_fits, ELVIgrow_bins, title = "ELVI")

FESUgrow_minus_byyear <- grow_minus_byyear(FESUgrow_fits, FESUgrow_bins, title = "FESU")
FESUgrow_plus_byyear <- grow_plus_byyear(FESUgrow_fits, FESUgrow_bins, title = "FESU")
FESUgrow_mean <- grow_mean(FESUgrow_fits, FESUgrow_bins, title = "FESU")

LOARgrow_minus_byyear <- grow_minus_byyear(LOARgrow_fits, LOARgrow_bins, title = "LOAR")
LOARgrow_plus_byyear <- grow_plus_byyear(LOARgrow_fits, LOARgrow_bins, title = "LOAR")
LOARgrow_mean <- grow_mean(LOARgrow_fits, LOARgrow_bins, title = "LOAR")

POALgrow_minus_byyear <- grow_minus_byyear(POALgrow_fits, POALgrow_bins, title = "POAL")
POALgrow_plus_byyear <- grow_plus_byyear(POALgrow_fits, POALgrow_bins, title = "POAL")
POALgrow_mean <- grow_mean(POALgrow_fits, POALgrow_bins, title = "POAL")

POSYgrow_minus_byyear <- grow_minus_byyear(POSYgrow_fits, POSYgrow_bins, title = "POSY")
POSYgrow_plus_byyear <- grow_plus_byyear(POSYgrow_fits, POSYgrow_bins, title = "POSY")
POSYgrow_mean <- grow_mean(POSYgrow_fits, POSYgrow_bins, title = "POSY")

```

```{r growth raw and fits plot annotations, include = FALSE}
growmean <- grid.arrange(AGPEgrow_mean, ELRIgrow_mean, ELVIgrow_mean, FESUgrow_mean, LOARgrow_mean, POALgrow_mean, POSYgrow_mean, ncol = 1)
titlegrowmean <- annotate_figure(growmean, top = "Mean growth", left = "")

growminus <- grid.arrange(AGPEgrow_minus_byyear, ELRIgrow_minus_byyear, ELVIgrow_minus_byyear, FESUgrow_minus_byyear, LOARgrow_minus_byyear, POALgrow_minus_byyear, POSYgrow_minus_byyear, ncol = 1)
titlegrowminus <- annotate_figure(growminus, top = "E- growth by Year", left = "")

growplus <- grid.arrange(AGPEgrow_plus_byyear, ELRIgrow_plus_byyear, ELVIgrow_plus_byyear, FESUgrow_plus_byyear, LOARgrow_plus_byyear, POALgrow_plus_byyear, POSYgrow_plus_byyear, ncol = 1)
titlegrowplus <- annotate_figure(growplus, top = "E+ growth by Year", left = "")

growthfits <- grid.arrange(titlegrowmean, titlegrowminus, titlegrowplus, ncol = 3)
titlegrowthfits <- annotate_figure(growthfits, top = "growth", left = "")

```

```{r growth figures, echo=FALSE, fig.width = 4, fig.height = 4}
# titlegrowthfits

FESUgrow_mean
FESUgrow_minus_byyear
FESUgrow_plus_byyear

POALgrow_mean
POALgrow_minus_byyear
POALgrow_plus_byyear

POSYgrow_mean
POSYgrow_minus_byyear
POSYgrow_plus_byyear
```