## Title: Grass endophyte population model with a bayesian framework
## Purpose: Creates seed to seedling kernel written in STAN with mixed effects, 
## and does visualisation of posterior predictive checks
## Authors: Joshua and Tom
#############################################################

library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
library(bayesplot)
library(devtools)

invlogit<-function(x){exp(x)/(1+exp(x))}
logit = function(x) { log(x/(1-x)) }
#############################################################################################
####### Data manipulation to prepare data as lists for Stan models------------------
#############################################################################################

# Using seed_means and spike data to generate seed estimates for all plots and years




# For the non-Elymus species, this function uses the posteriors generated by the model and the measured reproductive data to estimate seed production (currently I'm generating this in three different ways because I'm not sure what the best way to incorporate the measurements is)
est_seed <- function(fit,data){
  post <- extract(fit)
  
  est <- data
  est$seedperspike_est <-sample(post$mu_seed, size = nrow(data))
  return(est)
}

est$seed_a<- as.integer(data$seedperspike*sample(fit$mu_spike, size = nrow(data))*data$flw)
est$seed_b <- as.integer(sample(fit$mu_seed, size = nrow(data))*data$spikeperinf*data$flw)
est$seed <- as.integer(sample(fit$mu_seed, size = nrow(data))*sample(fit$mu_spike, size = nrow(data))*data$flw) # this is the seed estimate I'm using for now.

return(est)
}


# calculate POAL seed estimate
POAL_seed_est <- est_seed(fit = smPOAL, data = POAL_seed_data)
select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)

# calculate POSY seed estimate
POSY_post <- as.data.frame(smPOSY)
POSY_seed_est <- est_seed(post = POSY_post, data = POSY_seed_data) %>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate FESU seed estimate
FESU_post <- as.data.frame(smFESU)
FESU_seed_est <- est_seed(post = FESU_post, data = FESU_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate LOAR seed estimate
LOAR_post <- as.data.frame(smLOAR)
LOAR_seed_est <- est_seed(post = LOAR_post, data = LOAR_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)


# calculate AGPE seed estimate
AGPE_post <- as.data.frame(smAGPE)
AGPE_seed_est <- est_seed(post = AGPE_post, data = AGPE_seed_data)%>% 
  select(-seed_a, -seed_b, -seedperspike_est, -spikeperinf_est, -seed_norma, -seed_normb, -seed_normc)



# For the Elymus species, this function uses the posteriors generated by the model and the measured reproductive data to estimate seed production (currently I'm generating this in three different ways because I'm not sure what the best way to incorporate the measurements is)
est_seed_Elymus <- function(post,data){
  set.seed(5-1-2019)
  est <- data
  est$seedperinf_est <-sample(post$mu_seed, size = nrow(data))
  est$seedperinf_normest <- rnorm(mean = mean(post$mu_seed), sd = mean(post$sigma_seed), n = nrow(data))
  est$seed_a <- as.integer(data$seedperinf*data$flw)
  est$seed <- as.integer(sample(post$mu_seed, size = nrow(data))*data$flw) #This is the seed estimate I'm using for now
  est$seed_normb <- as.integer(rnorm(mean = mean(post$mu_seed), sd = mean(post$sigma_seed), n= nrow(data))*data$flw)
  return(est)
}

# calculate ELRI seed estimate
ELRI_post <- as.data.frame(smELRI)
ELRI_seed_est <- est_seed_Elymus(post = ELRI_post, data = ELRI_seed_data)%>% 
  select(-seed_a, -seedperinf_est, -seedperinf_normest,  -seed_normb)


# calculate ELVI seed estimate
ELVI_post <- as.data.frame(smELVI)
ELVI_seed_est <- est_seed_Elymus(post = ELVI_post, data = ELVI_seed_data)%>% 
  select(-seed_a, -seedperinf_est, -seedperinf_normest,  -seed_normb)





# Now I am going to merge the seed estimates for the different species into one dataframe. This will be merged with endo_demog_long for the seed to seedling transition rate.
seed_est_data <- ELVI_seed_est %>% 
  merge(ELRI_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(AGPE_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(FESU_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(LOAR_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(POAL_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE) %>% 
  merge(POSY_seed_est, by = c("plot","tag", "species", "endo_01", "endo_index", "year", "year_index", "seedperspike", "seedperinf", "spikeperinf", "flw", "samplesize", "plot_index", "seed" ),all = TRUE)


# View(seed_est_data)
# getting a dataframe with seed_t and seed_t1
seed_est_t1 <-seed_est_data %>%
  filter(year!= min(year)) %>% 
  rename(year_t1 = year, seed_t1 = seed, flw_t1 = flw) %>%  
  mutate(year_t = year_t1 - 1) %>% 
  select(-samplesize, -seedperinf, -seedperspike, -spikeperinf, -year_index)

seed_est_t <- seed_est_data %>%
  filter(year != max(year)) %>% 
  rename(year_t = year, seed_t = seed, flw_t = flw) %>% 
  mutate(year_t1 = year_t + 1) %>% 
  select(-samplesize, -seedperinf, -seedperspike, -spikeperinf, -year_index)


seed_estmerge <- seed_est_t1 %>% 
  full_join(seed_est_t, by = c("plot", "tag", "endo_01", "endo_index", "year_t", "year_t1", "species", "plot_index"),
            all.x = all, all.y = all)




# I'm going to merge this with the main data frame
# This needs to be merged with the rest of the flower data.
LTREB_endodemog <-  read.csv(file = "/Users/joshuacfowler/Dropbox/EndodemogData/Fulldataplusmetadata/endo_demog_long.csv")

LTREB_data_seed_est <- LTREB_endodemog %>% 
  rename(tag = id) %>% 
  select(-seed_t, -seed_t1, -flw_t1) %>% 
  merge(seed_estmerge, by = c("plot", "tag", "species", "year_t", "year_t1"), all = TRUE)
# View(LTREB_data_seed_est)


hist(AGPE_seed_est$seed)
hist(ELVI_seed_est$seed)
hist(ELRI_seed_est$seed)
hist(LOAR_seed_est$seed)
hist(POAL_seed_est$seed)
hist(POSY_seed_est$seed)
hist(FESU_seed_est$seed)





## Load in full data frame
LTREB_endodemog <-read.csv(file = "/Users/joshuacfowler/Dropbox/EndodemogData/Fulldataplusmetadata/endo_demog_long.csv")
LTREB_endodemog <- LTREB_data_seed_est

#"C:/Users/MillerLab/Desktop/Endodemog-master/endo_demog_long.csv"
#"/Users/joshuacfowler/Dropbox/EndodemogData/Fulldataplusmetadata/endo_demog_long.csv")
str(LTREB_endodemog)
dim(LTREB_endodemog)

## Clean up the main data frame for NA's, other small data entry errors, and change standardize the coding for variables.
LTREB_data <- LTREB_endodemog %>% 
  mutate(size_t, logsize_t = log(size_t)) %>% 
  mutate(size_t1, logsize_t1 = log(size_t1)) %>%  
  mutate(surv_t1 = as.integer(recode(surv_t1, "0" = 0, "1" =1, "2" = 1, "4" = 1))) %>% 
  mutate(endo_01 = as.integer(case_when(endo == "0" | endo == "minus" ~ 0,
                                        endo == "1"| endo =="plus" ~ 1))) %>% 
  filter(!is.na(endo_01)) %>% 
  mutate(endo_index = as.integer(as.factor(endo_01+1)))  %>% 
  mutate(species_index = as.integer(recode_factor(species,                   
                                                  "AGPE" = 1, "ELRI" = 2, "ELVI" = 3, 
                                                  "FESU" = 4, "LOAR" = 5, "POAL" = 6, 
                                                  "POSY" = 7))) %>% 
  mutate(year_t_index = as.integer(recode(year_t, 
                                          '2007' = 1, '2008' = 2, '2009' = 3, 
                                          '2010' = 4, '2011' = 5, '2012' = 6, 
                                          '2013' = 7, '2014' = 8, '2015' = 9, 
                                          '2016' = 10, '2017' = 11))) %>%             
  mutate(year_t1_index = as.integer(recode(year_t1, 
                                           '2008' = 2, '2009' = 3, '2010' = 4, 
                                           '2011' = 5, '2012' = 6, '2013' = 7, 
                                           '2014' = 8, '2015' = 9, '2016' = 10, 
                                           '2017' = 11, '2018' = 12))) %>%               
  mutate(origin_01 = as.integer(case_when(origin == "O" ~ 0, 
                                          origin == "R" ~ 1, 
                                          origin != "R" | origin != "O" ~ 1))) %>%   
  mutate(plot_fixed = (case_when(plot != "R" ~ plot, 
                                 plot == "R" ~ origin)))

dim(LTREB_data)

LTREB_data1 <- LTREB_data %>%
  group_by(species, plot_fixed, year_t, year_t_index, year_t1, year_t1_index, endo_01, endo_index) %>% 
  summarize(tot_seed_t = as.integer(round(sum(seed_t, na.rm = TRUE))),
            tot_recruit_t1 = length((origin_01 == "1"& year_t == birth)),
            samplesize = n()) %>% 
  filter(tot_seed_t>tot_recruit_t1)

dim(LTREB_data1)

# View(LTREB_data1)

#########################################################################################################
# Split up the main dataframe by species and recode plot to be used as an index for each species
AGPE_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "AGPE") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==2~1, year_t_index ==3~2, year_t_index ==4~3, year_t_index ==5~4, year_t_index ==6~5, year_t_index ==7~6, year_t_index ==8~7, year_t_index ==9~8)) %>% 
  mutate(plot_index = case_when(plot_fixed == 111 ~ 1, plot_fixed ==112 ~2, plot_fixed ==113 ~ 3, plot_fixed ==114 ~ 4, plot_fixed ==115 ~ 5,plot_fixed == 116 ~ 6, plot_fixed ==117~ 7, plot_fixed ==118 ~ 8, plot_fixed ==119 ~ 9,plot_fixed == 120 ~ 10))
ELRI_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "ELRI") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==2~1, year_t_index ==3~2, year_t_index ==4~3, year_t_index ==5~4, year_t_index ==6~5, year_t_index ==7~6, year_t_index ==8~7, year_t_index ==9~8)) %>% 
  mutate(plot_index = case_when(plot_fixed == 101 ~ 1, plot_fixed ==102 ~2, plot_fixed ==103 ~ 3, plot_fixed ==104 ~ 4, plot_fixed ==105 ~ 5,plot_fixed == 106 ~ 6, plot_fixed ==107~ 7, plot_fixed ==108 ~ 8, plot_fixed ==109 ~ 9,plot_fixed == 110 ~ 10)) 
ELVI_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "ELVI") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==3~1, year_t_index ==4~2, year_t_index ==5~3, year_t_index ==6~4, year_t_index ==7~5, year_t_index ==8~6, year_t_index ==9~7)) %>% 
  mutate(plot_index = case_when(plot_fixed == 91 ~ 1, plot_fixed ==92 ~2, plot_fixed ==93 ~ 3, plot_fixed ==94 ~ 4, plot_fixed ==95 ~ 5,plot_fixed == 96 ~ 6, plot_fixed ==97~ 7, plot_fixed ==98 ~ 8, plot_fixed ==99 ~ 9,plot_fixed == 100 ~ 10, plot_fixed == 101 ~ 11))
FESU_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "FESU") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==3~1, year_t_index ==4~2, year_t_index ==5~3, year_t_index ==6~4, year_t_index ==7~5, year_t_index ==8~6, year_t_index ==9~7)) %>% 
  mutate(plot_index = case_when(plot_fixed == 121 ~ 1, plot_fixed ==122 ~2, plot_fixed ==123 ~ 3, plot_fixed ==124 ~ 4, plot_fixed ==125 ~ 5,plot_fixed == 126 ~ 6, plot_fixed ==127~ 7, plot_fixed ==128 ~ 8, plot_fixed ==129 ~ 9,plot_fixed == 130 ~ 10)) 
LOAR_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "LOAR") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==2~1, year_t_index ==3~2, year_t_index ==4~3, year_t_index ==5~4, year_t_index ==6~5, year_t_index ==7~6, year_t_index ==8~7, year_t_index ==9~8)) %>% 
  mutate(plot_index = case_when(plot_fixed == 31 ~ 1, plot_fixed ==32 ~2, plot_fixed ==33 ~ 3, plot_fixed ==34 ~ 4, plot_fixed ==35 ~ 5,plot_fixed == 36 ~ 6, plot_fixed ==37~ 7, plot_fixed ==38 ~ 8, plot_fixed ==39 ~ 9,plot_fixed == 40 ~ 10, plot_fixed == 41 ~11,  plot_fixed == 42 ~12, plot_fixed == 43 ~13, plot_fixed == 44 ~14,)) 
POAL_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "POAL") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==2~1, year_t_index ==3~2, year_t_index ==4~3, year_t_index ==5~4, year_t_index ==6~5, year_t_index ==7~6, year_t_index ==8~7, year_t_index ==9~8)) %>% 
  mutate(plot_index = case_when(plot_fixed == 3 ~ 1, plot_fixed ==4 ~2, plot_fixed ==8 ~ 3, plot_fixed ==9 ~ 4, plot_fixed ==10 ~ 5,plot_fixed == 11 ~ 6, plot_fixed ==15~ 7, plot_fixed ==16~ 8, plot_fixed ==17~ 9, plot_fixed ==151 ~ 10, plot_fixed ==152 ~ 11,plot_fixed == 153 ~ 12, plot_fixed == 154 ~13,  plot_fixed == 155 ~14, plot_fixed == 156 ~15, plot_fixed == 157 ~16,plot_fixed == 158 ~17, plot_fixed == 19 ~18, )) 
POSY_s_to_s_data <- LTREB_data1 %>% 
  filter(species == "POSY") %>% 
  mutate(year_t_index_new = case_when(year_t_index ==2~1, year_t_index ==3~2, year_t_index ==4~3, year_t_index ==5~4, year_t_index ==6~5, year_t_index ==7~6, year_t_index ==8~7, year_t_index ==9~8)) %>% 
  mutate(plot_index = case_when(plot_fixed == 1 ~ 1, plot_fixed ==2 ~2, plot_fixed ==5 ~ 3, plot_fixed ==6 ~ 4, plot_fixed ==7 ~ 5,plot_fixed == 12 ~ 6, plot_fixed ==13~ 7, plot_fixed ==14 ~ 8, plot_fixed ==18 ~ 9,plot_fixed == 20 ~ 10, plot_fixed == 141 ~ 11, plot_fixed == 142 ~12,  plot_fixed == 143 ~13, plot_fixed == 144 ~14, plot_fixed == 145 ~15,plot_fixed == 146 ~16,plot_fixed == 147 ~17,plot_fixed == 148 ~18,plot_fixed == 149 ~19,plot_fixed == 150 ~20,))



# Create data lists to be used for the Stan model
AGPE_s_to_s_data_list <- list(tot_recruit_t1 = AGPE_s_to_s_data$tot_recruit_t1,
                            tot_seed_t = AGPE_s_to_s_data$tot_seed_t,
                            endo_01 = AGPE_s_to_s_data$endo_01,
                            endo_index = AGPE_s_to_s_data$endo_index,
                            year_t = AGPE_s_to_s_data$year_t_index_new,
                            plot = AGPE_s_to_s_data$plot_index,
                            N = nrow(AGPE_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(AGPE_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(AGPE_s_to_s_data$year_t_index)),
                            nPlot = length(unique(AGPE_s_to_s_data$plot_index)),
                            nEndo =   length(unique(AGPE_s_to_s_data$endo_01)))
str(AGPE_s_to_s_data_list)

ELRI_s_to_s_data_list <- list(tot_recruit_t1 = ELRI_s_to_s_data$tot_recruit_t1,
                            tot_seed_t = ELRI_s_to_s_data$tot_seed_t,
                            endo_01 = ELRI_s_to_s_data$endo_01,
                            endo_index = ELRI_s_to_s_data$endo_index,
                            year_t = ELRI_s_to_s_data$year_t_index_new,
                            plot = ELRI_s_to_s_data$plot_index,
                            N = nrow(ELRI_s_to_s_data),
                            K = 3L,
                            lowerlimit = 1L,
                            nYear = length(unique(ELRI_s_to_s_data$year_t_index)),
                            nPlot = length(unique(ELRI_s_to_s_data$plot_index)),
                            nEndo =   length(unique(ELRI_s_to_s_data$endo_01)))
str(ELRI_s_to_s_data_list)

ELVI_s_to_s_data_list <- list(tot_recruit_t1 = ELVI_s_to_s_data$tot_recruit_t1,
                            tot_seed_t = ELVI_s_to_s_data$tot_seed_t,
                            endo_01 = ELVI_s_to_s_data$endo_01,
                            endo_index = ELVI_s_to_s_data$endo_index,
                            year_t = ELVI_s_to_s_data$year_t_index_new,
                            plot = ELVI_s_to_s_data$plot_index,
                            N = nrow(ELVI_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(ELVI_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(ELVI_s_to_s_data$year_t_index)),
                            nPlot = 10L,
                            nEndo =   length(unique(ELVI_s_to_s_data$endo_01)))
str(ELVI_s_to_s_data_list)

FESU_s_to_s_data_list <- list(tot_recruit_t1 = FESU_s_to_s_data$tot_recruit_t1,
                              tot_seed_t = FESU_s_to_s_data$tot_seed_t,
                            endo_01 = FESU_s_to_s_data$endo_01,
                            endo_index = FESU_s_to_s_data$endo_index,
                            year_t = FESU_s_to_s_data$year_t_index_new,
                            plot = FESU_s_to_s_data$plot_index,
                            N = nrow(FESU_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(FESU_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(FESU_s_to_s_data$year_t_index)),
                            nPlot = length(unique(FESU_s_to_s_data$plot_index)),
                            nEndo =   length(unique(FESU_s_to_s_data$endo_01)))
str(FESU_s_to_s_data_list)

LOAR_s_to_s_data_list <- list(tot_recruit_t1 = LOAR_s_to_s_data$tot_recruit_t1,
                              tot_seed_t = LOAR_s_to_s_data$tot_seed_t,
                            endo_01 = LOAR_s_to_s_data$endo_01,
                            endo_index = LOAR_s_to_s_data$endo_index,
                            year_t = LOAR_s_to_s_data$year_t_index_new,
                            plot = LOAR_s_to_s_data$plot_index,
                            N = nrow(LOAR_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(LOAR_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(LOAR_s_to_s_data$year_t_index)),
                            nPlot = length(unique(LOAR_s_to_s_data$plot_index)),
                            nEndo =   length(unique(LOAR_s_to_s_data$endo_01)))
str(LOAR_s_to_s_data_list)

POAL_s_to_s_data_list <- list(tot_recruit_t1 = POAL_s_to_s_data$tot_recruit_t1,
                              tot_seed_t = POAL_s_to_s_data$tot_seed_t,
                            endo_01 = POAL_s_to_s_data$endo_01,
                            endo_index = POAL_s_to_s_data$endo_index,
                            year_t = POAL_s_to_s_data$year_t_index_new,
                            plot = POAL_s_to_s_data$plot_index,
                            N = nrow(POAL_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(POAL_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(POAL_s_to_s_data$year_t_index)),
                            nPlot = length(unique(POAL_s_to_s_data$plot_index)),
                            nEndo =   length(unique(POAL_s_to_s_data$endo_01)))
str(POAL_s_to_s_data_list)

POSY_s_to_s_data_list <- list(tot_recruit_t1 = POSY_s_to_s_data$tot_recruit_t1,
                              tot_seed_t = POSY_s_to_s_data$tot_seed_t,
                            endo_01 = POSY_s_to_s_data$endo_01,
                            endo_index = POSY_s_to_s_data$endo_index,
                            year_t = POSY_s_to_s_data$year_t_index_new,
                            plot = POSY_s_to_s_data$plot_index,
                            N = nrow(POSY_s_to_s_data),
                            K = 3L,
                            lowerlimit = as.integer(min(POSY_s_to_s_data$tot_recruit_t1)),
                            nYear = length(unique(POSY_s_to_s_data$year_t_index)),
                            nPlot = length(unique(POSY_s_to_s_data$plot_index)),
                            nEndo =   length(unique(POSY_s_to_s_data$endo_01)))
str(POSY_s_to_s_data_list)



# Tables to see how the data is spread over years
table(AGPE_s_to_s_data$endo_01, AGPE_s_to_s_data$year_t_index_new)
table(ELRI_s_to_s_data$endo_01, ELRI_s_to_s_data$year_t_index_new)
table(ELVI_s_to_s_data$endo_01, ELVI_s_to_s_data$year_t_index_new)
table(FESU_s_to_s_data$endo_01, FESU_s_to_s_data$year_t_index_new)
table(LOAR_s_to_s_data$endo_01, LOAR_s_to_s_data$year_t_index_new)
table(POAL_s_to_s_data$endo_01, POAL_s_to_s_data$year_t_index_new)
table(POSY_s_to_s_data$endo_01, POSY_s_to_s_data$year_t_index_new)

#########################################################################################################
# GLMM for tot_recruit_t1~ tot_seed_t1 +Endo  with year and plot random effects------------------------------
#########################################################################################################
## run this code recommended to optimize computer system settings for MCMC
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
set.seed(123)
## MCMC settings
ni <- 1000
nb <- 500
nc <- 3

# Stan model -------------
## here is the Stan model

sink("endodemog_s_to_s.stan")
cat("
    data { 
    int<lower=0> N;                       // number of observations
    int<lower=0> K;                       // number of predictors
    int<lower=0> lowerlimit;                         //lower limit for truncated negative binomial
    int<lower=0> nYear;                       // number of years
    int<lower=0, upper=11> year_t[N];         // year of observation
    int<lower=0> nEndo;                       // number of endo treatments
    int<lower=1, upper=2> endo_index[N];          // index for endophyte effect
    int<lower=0> nPlot;                         // number of plots
    int<lower=0> plot[N];                   // plot of observation
    int<lower=0> tot_recruit_t1[N];      // total recruits into the plot (response)
    int<lower=0> tot_seed_t[N];             // total seeds in plot (predictor)
    int<lower=0,upper=1> endo_01[N];            // plant endophyte status (predictor)
    }

    parameters {
    vector[2] beta;                     // predictor parameters
    vector[nYear] tau_year[nEndo];      // random year effect
    real<lower=0> sigma_e[nEndo];        //year variance by endophyte effect
    vector[nPlot] tau_plot;        // random plot effect
    real<lower=0> sigma_p;          // plot variance effect
    }
    
    transformed parameters{
    // Linear Predictor
    vector[N] mu;
    
    for(n in 1:N){
      mu[n] = beta[1] + beta[2]*endo_01[n]
      + tau_year[endo_index[n],year_t[n]]
      + tau_plot[plot[n]];
    }
    
    }

    model {
  
    // Priors
    beta ~ normal(0,1);      // prior for predictor intercepts
    tau_plot ~ normal(0,sigma_p);   // prior for plot random effects
    to_vector(tau_year[1]) ~ normal(0,sigma_e[1]);   // prior for E- year random effects
    to_vector(tau_year[2]) ~ normal(0,sigma_e[2]);   // prior for E+ year random effects
    
    // Likelihood
    tot_recruit_t1 ~ binomial_logit(tot_seed_t, mu);
    }
    
    generated quantities{
    }
  
    ", fill = T)
sink()

stanmodel <- stanc("endodemog_s_to_s.stan")



## Run the model by calling stan()
## and save the output to .rds files so that they can be called laters

smAGPE <- stan(file = "endodemog_s_to_s.stan", data = AGPE_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
ELR# saveRDS(smAGPE, file = "endodemog_s_to_s_AGPE.rds")

smELRI <- stan(file = "endodemog_s_to_s.stan", data = ELRI_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smELRI, file = "endodemog_s_to_s_ELRI.rds")

smELVI <- stan(file = "endodemog_s_to_s.stan", data = ELVI_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smELVI, file = "endodemog_s_to_s_ELVI.rds")

smFESU <- stan(file = "endodemog_s_to_s.stan", data = FESU_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smFESU, file = "endodemog_s_to_s_FESU.rds")

smLOAR <- stan(file = "endodemog_s_to_s.stan", data = LOAR_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smLOAR, file = "endodemog_s_to_s_LOAR.rds")

smPOAL <- stan(file = "endodemog_s_to_s.stan", data = POAL_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smPOAL, file = "endodemog_s_to_s_POAL.rds")

smPOSY <- stan(file = "endodemog_s_to_s.stan", data = POSY_s_to_s_data_list,
               iter = ni, warmup = nb, chains = nc, save_warmup = FALSE)
# saveRDS(smPOSY, file = "endodemog_s_to_s_POSY.rds")

print(sm)
summary(sm)
print(sm, pars = "sigma_e")





## to read in model output without rerunning models
smPOAL <- readRDS(file = "model_run_MAR7/endodemog_surv_POAL.rds")
smPOSY <- readRDS(file = "model_run_MAR7/endodemog_surv_POSY.rds")
smLOAR <- readRDS(file = "model_run_MAR7/endodemog_surv_LOAR.rds")
smELVI <- readRDS(file = "model_run_MAR7/endodemog_surv_ELVI.rds")
smELRI <- readRDS(file = "model_run_MAR7/endodemog_surv_ELRI.rds")
smFESU <- readRDS(file = "model_run_MAR7/endodemog_surv_FESU.rds")
smAGPE <- readRDS(file = "model_run_MAR7/endodemog_surv_AGPE.rds")



